name: Java Build and Test Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'Notas'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'Notas'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Run Tests with Maven
      run: mvn -B package --file pom.xml